#!/usr/bin/env bash
#
# Reads config from $CONFIGS/topics and $CONFIGS/acls
# and creates the specified topics and ACLs.

source "$TOOLS_BIN/lib/logging.sh"

TOOLS="${STACK_PATH}/tools"

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function expand_perms {
  case "$1" in
    consumer) echo "READ DESCRIBE";;
    producer) echo "WRITE DESCRIBE CREATE";;
    *) echo "$1";;
  esac
}

# -----------------------------------------------------
# Functions
# -----------------------------------------------------

function create_topics {
  local file topic partitions replication

  for file in "$CONFIGS/topics/"*.yml "$CONFIGS/topics/"*.yaml; do
    [ -e "$file" ] || continue

    topic=$(yq -r '.topic' "$file")
    partitions=$(yq -r '.partitions' "$file")
    replication=$(yq -r '.replication_factor' "$file")

    if ! "$TOOLS/kafka-topics" --list \
          | sed 's/\r$//' \
          | grep -qx "$topic"; then

      log_info "Creating topic: $topic"
      "$TOOLS/kafka-topics" \
        --create \
        --topic "$topic" \
        --partitions "$partitions" \
        --replication-factor "$replication"
    else
      log_info "Topic already exists: $topic"
    fi
  done
}

function create_acls {
  local file principal user group topics perms fqdn_hosts topic perm expanded operation all_exist

  for file in "$CONFIGS/acls/"*.yml "$CONFIGS/acls/"*.yaml; do
    [ -e "$file" ] || continue

    principal=$(yq -r '.principal' "$file")
    user=${principal#"User:"}
    group=$(yq -r '.group' "$file")
    hosts=$(yq -r '.hosts[]' "$file")

    mapfile -t topics < <(yq -r '.topics[]' "$file")
    mapfile -t perms < <(yq -r '.permissions[]' "$file")

    fqdn_hosts=""
    for host in $hosts; do
      fqdn_hosts+="$host $host.$DOMAIN "
    done

    if [ ! -f "$SECRETS/$user-keystore.jks" ]; then
      log_info "Creating new certs and keystore..."
      "$TOOLS/make-user" "$user" "$fqdn_hosts"
    fi

    for topic in "${topics[@]}"; do
      for perm in "${perms[@]}"; do
        read -r -a expanded <<<"$(expand_perms "$perm")"

        all_exist=true
        for operation in "${expanded[@]}"; do
          if ! "$TOOLS/kafka-acls" --list --topic "$topic"  \
              | grep "principal=$principal" \
              | grep -q "operation=$operation"; then
            all_exist=false
          fi
        done

        if $all_exist; then
          log_info "All ACLs for $perm already exist for $principal on $topic."
          continue
        fi

        log_info "Applying ACL: $perm on $topic for $principal"
        "$TOOLS/kafka-acls" \
          --add \
          --allow-principal "$principal" \
          --"$perm" \
          --topic "$topic" \
          --group "$group"
      done
    done
  done
}

# -----------------------------------------------------
# Main
# -----------------------------------------------------

log_info "Creating topics..."
create_topics

log_info "Creating users and ACLs"
create_acls
