#!/usr/bin/env bash
#
# Usage: make-user <user> <hostname1> [hostname2 ...]

USER="$1"
shift
HOSTS=$@

make-keystore "$USER" $HOSTS -o "$SECRETS"

KEYSTORE="/etc/kafka/secrets/${USER}-keystore.jks"
KEYSTORE_PASS="$(cat "$SECRETS/${USER}-keystore.pass")"


TRUSTSTORE="/etc/kafka/secrets/kafka-truststore.jks"
TRUSTSTORE_PASS="$(cat "$SECRETS/kafka-keystore.pass")"


PROPERTIES="$SECRETS/${USER}.properties"

cat > "$PROPERTIES" <<EOF
security.protocol=SSL

ssl.keystore.location=${KEYSTORE}
ssl.keystore.password=${KEYSTORE_PASS}

ssl.truststore.location=${TRUSTSTORE}
ssl.truststore.password=${TRUSTSTORE_PASS}
EOF
